export function getStateFromPin(pin: string): string {
  if (pin.length < 2) return ''
  const p = parseInt(pin.slice(0, 2), 10)
  if (p === 11) return 'Delhi'
  if (p === 12 || p === 13) return 'Haryana'
  if (p >= 14 && p <= 16) return 'Punjab'
  if (p === 17) return 'Himachal Pradesh'
  if (p === 18 || p === 19) return 'Jammu & Kashmir'
  if (p >= 20 && p <= 28) return 'Uttar Pradesh'
  if (p >= 30 && p <= 34) return 'Rajasthan'
  if (p >= 36 && p <= 39) return 'Gujarat'
  if (p >= 40 && p <= 44) return 'Maharashtra'
  if (p >= 45 && p <= 48) return 'Madhya Pradesh'
  if (p === 49) return 'Chhattisgarh'
  if (p === 50) return 'Telangana'
  if (p >= 51 && p <= 53) return 'Andhra Pradesh'
  if (p >= 56 && p <= 59) return 'Karnataka'
  if (p >= 60 && p <= 65) return 'Tamil Nadu'
  if (p >= 66 && p <= 69) return 'Kerala'
  if (p >= 70 && p <= 74) return 'West Bengal'
  if (p === 75 || p === 76) return 'Odisha'
  if (p >= 77 && p <= 79) return 'Assam / North East'
  if (p === 80 || p === 81 || (p >= 84 && p <= 85)) return 'Bihar'
  if (p === 82 || p === 83) return 'Jharkhand'
  return ''
}
